// =========================================
// Seed exercise library — comprehensive
// Each exercise has:
//   id, name, muscleGroup, equipment,
//   primary[]  — list of region keys highlighted on the silhouette
//   view       — 'front' | 'back' — preferred figure orientation
//   description, instructions, keywords
// =========================================

const MUSCLE_GROUPS = ['All', 'Chest', 'Back', 'Shoulders', 'Arms', 'Legs', 'Core', 'Cardio', 'Full Body'];

const SEED_EXERCISES = [

  // ============ CHEST ============
  { id: 'bench-press', name: 'Barbell Bench Press', muscleGroup: 'Chest', equipment: 'Barbell', view: 'front', primary: ['chest','shoulders','triceps'],
    description: 'The cornerstone horizontal press — builds the entire chest, front delts and triceps.',
    instructions: '1. Lie flat, eyes under the bar.\n2. Grip slightly wider than shoulders.\n3. Unrack and lower the bar to mid-chest with control.\n4. Press to lockout with shoulder blades retracted.',
    keywords: ['bench','flat','barbell'] },
  { id: 'incline-bench-press', name: 'Incline Barbell Press', muscleGroup: 'Chest', equipment: 'Barbell', view: 'front', primary: ['chest','shoulders','triceps'],
    description: 'Bench set to 30-45° — biases the upper chest and front delts.',
    instructions: '1. Set bench to 30°.\n2. Grip just wider than shoulders.\n3. Lower to upper-chest with control.\n4. Press straight up to lockout.',
    keywords: ['incline','upper chest'] },
  { id: 'decline-bench-press', name: 'Decline Barbell Press', muscleGroup: 'Chest', equipment: 'Barbell', view: 'front', primary: ['chest','triceps'],
    description: 'Lower-chest emphasis — easier on the shoulders for many lifters.',
    instructions: '1. Lock feet under pads.\n2. Lower the bar to lower chest.\n3. Press to lockout.',
    keywords: ['decline'] },
  { id: 'db-bench-press', name: 'Dumbbell Bench Press', muscleGroup: 'Chest', equipment: 'Dumbbell', view: 'front', primary: ['chest','shoulders','triceps'],
    description: 'Free-weight press with greater stretch and unilateral balance demand.',
    instructions: '1. Sit, kick dumbbells up to shoulders, lie back.\n2. Lower in line with mid-chest, deep stretch.\n3. Press up and slightly together.',
    keywords: ['dumbbell','db'] },
  { id: 'db-incline-press', name: 'Incline Dumbbell Press', muscleGroup: 'Chest', equipment: 'Dumbbell', view: 'front', primary: ['chest','shoulders','triceps'],
    description: 'Incline press with dumbbells for a deeper stretch on the upper chest.',
    instructions: '1. Bench at 30°.\n2. Lower with elbows ~45° to torso.\n3. Press to lockout.',
    keywords: ['incline','dumbbell'] },
  { id: 'db-fly', name: 'Dumbbell Fly', muscleGroup: 'Chest', equipment: 'Dumbbell', view: 'front', primary: ['chest'],
    description: 'Isolation for the pecs through a wide stretch.',
    instructions: '1. Lie flat, dumbbells over chest, slight elbow bend.\n2. Open the arms wide in an arc.\n3. Squeeze pecs to bring them back together.',
    keywords: ['fly','flye'] },
  { id: 'cable-fly', name: 'Cable Fly', muscleGroup: 'Chest', equipment: 'Cable', view: 'front', primary: ['chest'],
    description: 'Constant-tension chest isolation with a strong contraction.',
    instructions: '1. Set pulleys high (or mid).\n2. Step forward, slight forward lean.\n3. Arc the handles together in front of chest.\n4. Slow return to a deep stretch.',
    keywords: ['cable','fly','crossover'] },
  { id: 'cable-crossover', name: 'Cable Crossover', muscleGroup: 'Chest', equipment: 'Cable', view: 'front', primary: ['chest'],
    description: 'High-to-low cable fly — emphasises the lower chest.',
    instructions: '1. Pulleys high, handle in each hand.\n2. Step forward, slight lean.\n3. Bring handles down and across the body.',
    keywords: ['crossover','cable'] },
  { id: 'pec-deck', name: 'Pec Deck', muscleGroup: 'Chest', equipment: 'Machine', view: 'front', primary: ['chest'],
    description: 'Fixed-arc chest isolation, very easy to learn.',
    instructions: '1. Set pads at chest height.\n2. Press the pads together with elbows.\n3. Slow return.',
    keywords: ['pec','deck','machine fly'] },
  { id: 'chest-press-machine', name: 'Chest Press Machine', muscleGroup: 'Chest', equipment: 'Machine', view: 'front', primary: ['chest','shoulders','triceps'],
    description: 'Plate-loaded or selectorised pressing — safe and effective to push close to failure.',
    instructions: '1. Adjust seat so handles align with mid-chest.\n2. Press out to near lockout.\n3. Return to a deep stretch.',
    keywords: ['machine','chest press'] },
  { id: 'pushup', name: 'Push-Up', muscleGroup: 'Chest', equipment: 'Bodyweight', view: 'front', primary: ['chest','shoulders','triceps','abs'],
    description: 'The default upper-body bodyweight movement.',
    instructions: '1. Hands under shoulders.\n2. Brace core, body in a straight line.\n3. Lower until chest grazes the floor.\n4. Press back up.',
    keywords: ['pushup','push up'] },
  { id: 'incline-pushup', name: 'Incline Push-Up', muscleGroup: 'Chest', equipment: 'Bodyweight', view: 'front', primary: ['chest','shoulders','triceps'],
    description: 'Easier push-up variation with hands elevated.',
    instructions: '1. Hands on a bench or sturdy surface.\n2. Lower chest to the bench.\n3. Press back up.',
    keywords: ['incline pushup'] },
  { id: 'decline-pushup', name: 'Decline Push-Up', muscleGroup: 'Chest', equipment: 'Bodyweight', view: 'front', primary: ['chest','shoulders','triceps'],
    description: 'Feet elevated — biases the upper chest and shoulders.',
    instructions: '1. Feet on a bench or box.\n2. Hands under shoulders.\n3. Lower chest to the floor, press back up.',
    keywords: ['decline pushup'] },
  { id: 'dips-chest', name: 'Chest Dip', muscleGroup: 'Chest', equipment: 'Bodyweight', view: 'front', primary: ['chest','triceps','shoulders'],
    description: 'Slight forward lean variation — heavy chest emphasis.',
    instructions: '1. Lean forward 30°.\n2. Lower until shoulders are at elbow height.\n3. Press up without locking out.',
    keywords: ['dips','chest dip'] },
  { id: 'svend-press', name: 'Svend Press', muscleGroup: 'Chest', equipment: 'Bodyweight', view: 'front', primary: ['chest'],
    description: 'Squeeze press with plates — inner-chest activation drill.',
    instructions: '1. Press two plates together at chest.\n2. Extend forward squeezing plates.\n3. Return slowly.',
    keywords: ['svend','squeeze press'] },
  { id: 'floor-press', name: 'Floor Press', muscleGroup: 'Chest', equipment: 'Barbell', view: 'front', primary: ['chest','triceps'],
    description: 'Press from the floor — reduced ROM, big triceps and lockout work.',
    instructions: '1. Lie on the floor under the bar.\n2. Lower until upper arms touch the floor.\n3. Press to lockout.',
    keywords: ['floor press'] },

  // ============ BACK ============
  { id: 'deadlift', name: 'Conventional Deadlift', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['back','lats','traps','glutes','hamstrings','forearms'],
    description: 'A full-body pull that builds the entire posterior chain.',
    instructions: '1. Mid-foot under the bar.\n2. Hinge down, grip just outside knees.\n3. Set back flat, chest up, lats tight.\n4. Drive the floor away, stand tall, lockout hips.',
    keywords: ['deadlift','dl'] },
  { id: 'sumo-deadlift', name: 'Sumo Deadlift', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['glutes','hamstrings','back','traps'],
    description: 'Wide-stance deadlift — shorter ROM, more quad and glute involvement.',
    instructions: '1. Wide stance, toes out.\n2. Grip inside legs.\n3. Set tall chest, drive knees out and stand.',
    keywords: ['sumo','deadlift'] },
  { id: 'rdl', name: 'Romanian Deadlift', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['hamstrings','glutes','back'],
    description: 'Hip-hinge focused — premier hamstring builder.',
    instructions: '1. Start tall with the bar at hips.\n2. Push hips back, soft knees, lower until hamstrings stretch.\n3. Drive hips forward to stand.',
    keywords: ['rdl','romanian','hinge'] },
  { id: 'stiff-leg-dl', name: 'Stiff-Leg Deadlift', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['hamstrings','glutes','back'],
    description: 'Like an RDL but with locked knees for a deeper hamstring stretch.',
    instructions: '1. Lock knees almost straight.\n2. Hinge until hamstrings stretch.\n3. Stand back up under control.',
    keywords: ['stiff','leg','sldl'] },
  { id: 'rack-pull', name: 'Rack Pull', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['back','traps','lats','forearms'],
    description: 'Partial deadlift from pins around knee height — heavy upper-back work.',
    instructions: '1. Set pins at knee height.\n2. Grip the bar, set the back flat.\n3. Drive hips through to lockout.',
    keywords: ['rack pull','partial deadlift'] },
  { id: 'pullup', name: 'Pull-Up', muscleGroup: 'Back', equipment: 'Bodyweight', view: 'back', primary: ['lats','back','biceps','rear-delts'],
    description: 'Premier vertical pull — overhand grip biases the lats.',
    instructions: '1. Hang with hands shoulder-width or slightly wider.\n2. Pull chest to bar with elbows down.\n3. Lower with full control.',
    keywords: ['pullup','pull up'] },
  { id: 'chinup', name: 'Chin-Up', muscleGroup: 'Back', equipment: 'Bodyweight', view: 'back', primary: ['lats','biceps','back'],
    description: 'Underhand pull-up — easier on the shoulders, more bicep involvement.',
    instructions: '1. Underhand grip, shoulder-width.\n2. Pull chin over the bar.\n3. Lower slowly.',
    keywords: ['chinup','chin up'] },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroup: 'Back', equipment: 'Cable', view: 'back', primary: ['lats','back','biceps'],
    description: 'Cable replacement for the pull-up.',
    instructions: '1. Grip the bar slightly wider than shoulders.\n2. Pull to upper chest, lats engaged.\n3. Slow return to a full stretch.',
    keywords: ['lat','pulldown'] },
  { id: 'wide-grip-pulldown', name: 'Wide-Grip Pulldown', muscleGroup: 'Back', equipment: 'Cable', view: 'back', primary: ['lats','back'],
    description: 'Wider grip biases the upper lats and rear delts.',
    instructions: '1. Wide overhand grip.\n2. Pull to upper chest.\n3. Slow controlled return.',
    keywords: ['wide pulldown'] },
  { id: 'close-grip-pulldown', name: 'Close-Grip Pulldown', muscleGroup: 'Back', equipment: 'Cable', view: 'back', primary: ['lats','biceps'],
    description: 'Neutral or close grip — emphasises lower lats and biceps.',
    instructions: '1. Use a V-handle.\n2. Pull to upper chest.\n3. Slow return.',
    keywords: ['close pulldown','v handle'] },
  { id: 'seated-cable-row', name: 'Seated Cable Row', muscleGroup: 'Back', equipment: 'Cable', view: 'back', primary: ['back','lats','rear-delts','biceps'],
    description: 'Horizontal pull for mid-back thickness.',
    instructions: '1. Sit tall, feet planted.\n2. Pull the handle to your stomach.\n3. Squeeze shoulder blades.\n4. Return slowly.',
    keywords: ['seated row','cable row'] },
  { id: 'bb-row', name: 'Bent-Over Barbell Row', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['back','lats','rear-delts','traps'],
    description: 'A heavy compound row that builds the entire back.',
    instructions: '1. Hinge forward to ~45°.\n2. Pull the bar to lower chest / upper abs.\n3. Lower under control.',
    keywords: ['bent over row','bb row'] },
  { id: 'pendlay-row', name: 'Pendlay Row', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['back','lats','traps'],
    description: 'Strict barbell row from a dead stop on the floor.',
    instructions: '1. Hinge to torso parallel to floor.\n2. Explosively row from the floor to lower chest.\n3. Return all the way down.',
    keywords: ['pendlay'] },
  { id: 't-bar-row', name: 'T-Bar Row', muscleGroup: 'Back', equipment: 'Machine', view: 'back', primary: ['back','lats','traps'],
    description: 'Hammer-grip rowing for back thickness.',
    instructions: '1. Straddle the bar, hinge to ~45°.\n2. Pull to chest.\n3. Lower with control.',
    keywords: ['t bar','tbar'] },
  { id: 'db-row', name: 'Single-Arm Dumbbell Row', muscleGroup: 'Back', equipment: 'Dumbbell', view: 'back', primary: ['lats','back','rear-delts','biceps'],
    description: 'Unilateral row — great for fixing imbalances.',
    instructions: '1. Brace one hand on a bench.\n2. Row dumbbell to hip.\n3. Squeeze, lower fully.',
    keywords: ['db row','one arm row'] },
  { id: 'chest-supported-row', name: 'Chest-Supported Row', muscleGroup: 'Back', equipment: 'Machine', view: 'back', primary: ['back','lats','rear-delts'],
    description: 'Removes lower-back fatigue, lets you push the back hard.',
    instructions: '1. Chest against the pad.\n2. Row to lower ribs.\n3. Slow return.',
    keywords: ['chest supported','row'] },
  { id: 'inverted-row', name: 'Inverted Row', muscleGroup: 'Back', equipment: 'Bodyweight', view: 'back', primary: ['back','lats','rear-delts','biceps'],
    description: 'Bodyweight horizontal pull — adjust angle to change difficulty.',
    instructions: '1. Hang under a bar at hip height.\n2. Pull chest to the bar.\n3. Lower with control.',
    keywords: ['inverted row','body row'] },
  { id: 'face-pull', name: 'Face Pull', muscleGroup: 'Back', equipment: 'Cable', view: 'back', primary: ['rear-delts','traps','back'],
    description: 'Rear delt and external rotator builder — great for shoulder health.',
    instructions: '1. Rope handle, set above head height.\n2. Pull to face, elbows high.\n3. Squeeze and return slowly.',
    keywords: ['face pull','rear delt'] },
  { id: 'straight-arm-pulldown', name: 'Straight-Arm Pulldown', muscleGroup: 'Back', equipment: 'Cable', view: 'back', primary: ['lats'],
    description: 'Lat isolation with extended arms.',
    instructions: '1. Stand back from a high pulley.\n2. Press the bar down in an arc.\n3. Slow return to overhead.',
    keywords: ['straight arm','pulldown'] },
  { id: 'shrug', name: 'Barbell Shrug', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['traps'],
    description: 'Direct trap builder.',
    instructions: '1. Stand tall, bar at hips.\n2. Shrug shoulders straight up.\n3. Squeeze and lower under control.',
    keywords: ['shrug','traps'] },
  { id: 'back-extension', name: 'Back Extension', muscleGroup: 'Back', equipment: 'Machine', view: 'back', primary: ['back','glutes','hamstrings'],
    description: 'Lower back, glute and hamstring builder.',
    instructions: '1. Set pads at hip crease.\n2. Hinge down then extend to neutral.\n3. Avoid hyper-extending.',
    keywords: ['hyperextension','back ext'] },
  { id: 'good-morning', name: 'Good Morning', muscleGroup: 'Back', equipment: 'Barbell', view: 'back', primary: ['hamstrings','glutes','back'],
    description: 'A hip hinge under a loaded bar on the back.',
    instructions: '1. Bar on upper back.\n2. Hinge forward with slight knee bend.\n3. Return by driving hips forward.',
    keywords: ['good morning'] },

  // ============ SHOULDERS ============
  { id: 'ohp', name: 'Overhead Press', muscleGroup: 'Shoulders', equipment: 'Barbell', view: 'front', primary: ['shoulders','triceps','traps','abs'],
    description: 'Standing barbell press — the gold standard for shoulder strength.',
    instructions: '1. Bar at front rack, elbows under the bar.\n2. Brace, press the bar overhead.\n3. Lock out with biceps near ears.',
    keywords: ['ohp','overhead press','military'] },
  { id: 'db-shoulder-press', name: 'Dumbbell Shoulder Press', muscleGroup: 'Shoulders', equipment: 'Dumbbell', view: 'front', primary: ['shoulders','triceps'],
    description: 'Seated or standing dumbbell press for shoulder development.',
    instructions: '1. Dumbbells at shoulder height.\n2. Press up, slight arc inward.\n3. Lower with control.',
    keywords: ['db press','shoulder'] },
  { id: 'arnold-press', name: 'Arnold Press', muscleGroup: 'Shoulders', equipment: 'Dumbbell', view: 'front', primary: ['shoulders'],
    description: 'Rotating dumbbell press that hits all three delt heads.',
    instructions: '1. Start palms facing you at chest.\n2. Press up while rotating palms outward.\n3. Reverse on the way down.',
    keywords: ['arnold press'] },
  { id: 'machine-shoulder-press', name: 'Machine Shoulder Press', muscleGroup: 'Shoulders', equipment: 'Machine', view: 'front', primary: ['shoulders','triceps'],
    description: 'Guided vertical press — easy to push close to failure.',
    instructions: '1. Adjust handles at shoulder height.\n2. Press up to near lockout.\n3. Lower under control.',
    keywords: ['machine shoulder'] },
  { id: 'lateral-raise', name: 'Dumbbell Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbell', view: 'front', primary: ['shoulders'],
    description: 'Isolates the side delts — width builder.',
    instructions: '1. Slight elbow bend, dumbbells at sides.\n2. Raise out to shoulder height, pinky slightly higher.\n3. Lower slowly.',
    keywords: ['lateral raise','side raise'] },
  { id: 'cable-lateral-raise', name: 'Cable Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Cable', view: 'front', primary: ['shoulders'],
    description: 'Constant-tension side delt isolation.',
    instructions: '1. Low pulley, cable across the body.\n2. Raise to shoulder height.\n3. Lower with control.',
    keywords: ['cable lateral'] },
  { id: 'front-raise', name: 'Front Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbell', view: 'front', primary: ['shoulders'],
    description: 'Isolation for the anterior delts.',
    instructions: '1. Dumbbells in front of thighs.\n2. Raise to shoulder height.\n3. Lower slowly.',
    keywords: ['front raise'] },
  { id: 'rear-delt-fly', name: 'Rear Delt Fly', muscleGroup: 'Shoulders', equipment: 'Dumbbell', view: 'back', primary: ['rear-delts','back'],
    description: 'Hinged or reverse-pec-deck rear delt isolation.',
    instructions: '1. Hinge forward, slight elbow bend.\n2. Open arms wide.\n3. Squeeze shoulder blades together.',
    keywords: ['rear delt','reverse fly'] },
  { id: 'reverse-pec-deck', name: 'Reverse Pec Deck', muscleGroup: 'Shoulders', equipment: 'Machine', view: 'back', primary: ['rear-delts','back'],
    description: 'Fixed-arc rear delt isolation.',
    instructions: '1. Chest against the pad, arms extended.\n2. Pull handles out to the sides.\n3. Squeeze and return.',
    keywords: ['reverse pec deck','rear delt machine'] },
  { id: 'upright-row', name: 'Upright Row', muscleGroup: 'Shoulders', equipment: 'Barbell', view: 'front', primary: ['shoulders','traps'],
    description: 'Pull the bar from waist to chest — hits delts and upper traps.',
    instructions: '1. Grip about shoulder width.\n2. Pull elbows high to chest height.\n3. Lower slowly.',
    keywords: ['upright row'] },
  { id: 'push-press', name: 'Push Press', muscleGroup: 'Shoulders', equipment: 'Barbell', view: 'front', primary: ['shoulders','triceps','quads'],
    description: 'Leg-drive assisted overhead press — handle heavier loads.',
    instructions: '1. Bar at front rack.\n2. Quick quarter dip.\n3. Drive bar overhead with the legs.',
    keywords: ['push press'] },
  { id: 'landmine-press', name: 'Landmine Press', muscleGroup: 'Shoulders', equipment: 'Barbell', view: 'front', primary: ['shoulders','chest','triceps'],
    description: 'Angled press — shoulder-friendly and very stable.',
    instructions: '1. Stand at the working end of the bar.\n2. Press the bar up and away.\n3. Lower under control.',
    keywords: ['landmine'] },

  // ============ ARMS / BICEPS ============
  { id: 'bb-curl', name: 'Barbell Curl', muscleGroup: 'Arms', equipment: 'Barbell', view: 'front', primary: ['biceps','forearms'],
    description: 'The classic biceps builder.',
    instructions: '1. Stand tall, elbows at sides.\n2. Curl the bar to shoulders.\n3. Lower slowly to full extension.',
    keywords: ['barbell curl','bb curl'] },
  { id: 'db-curl', name: 'Dumbbell Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'front', primary: ['biceps','forearms'],
    description: 'Bicep curl with supination.',
    instructions: '1. Curl with palm rotating from neutral to up.\n2. Squeeze top.\n3. Lower fully.',
    keywords: ['dumbbell curl','db curl'] },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'front', primary: ['biceps','forearms'],
    description: 'Neutral grip curl — biases brachialis and forearms.',
    instructions: '1. Palms face each other throughout.\n2. Curl up, squeeze.\n3. Lower under control.',
    keywords: ['hammer','neutral curl'] },
  { id: 'preacher-curl', name: 'Preacher Curl', muscleGroup: 'Arms', equipment: 'Barbell', view: 'front', primary: ['biceps'],
    description: 'Bench-supported curl — isolates the short head.',
    instructions: '1. Arms on the preacher pad.\n2. Curl up, slow lower.\n3. Avoid full lockout for tension.',
    keywords: ['preacher'] },
  { id: 'concentration-curl', name: 'Concentration Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'front', primary: ['biceps'],
    description: 'Seated single-arm curl, elbow braced against inner thigh.',
    instructions: '1. Sit, elbow against the thigh.\n2. Curl up to chest.\n3. Slow lower.',
    keywords: ['concentration'] },
  { id: 'cable-curl', name: 'Cable Curl', muscleGroup: 'Arms', equipment: 'Cable', view: 'front', primary: ['biceps'],
    description: 'Constant-tension curl with cables.',
    instructions: '1. Low pulley, EZ or straight bar.\n2. Curl to shoulders.\n3. Lower slowly.',
    keywords: ['cable curl'] },
  { id: 'ez-curl', name: 'EZ Bar Curl', muscleGroup: 'Arms', equipment: 'Barbell', view: 'front', primary: ['biceps','forearms'],
    description: 'Cambered-bar curl — wrist-friendly.',
    instructions: '1. Inner-grip on the camber.\n2. Curl up, squeeze, slow lower.',
    keywords: ['ez bar'] },
  { id: 'incline-db-curl', name: 'Incline Dumbbell Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'front', primary: ['biceps'],
    description: 'Incline bench curl — deep stretch on the long head.',
    instructions: '1. Bench at ~60°.\n2. Arms hanging straight down.\n3. Curl up without elbow flare.',
    keywords: ['incline curl'] },
  { id: 'spider-curl', name: 'Spider Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'front', primary: ['biceps'],
    description: 'Chest-down on incline bench — strong contraction at top.',
    instructions: '1. Lie chest-down on incline bench.\n2. Arms hang straight down.\n3. Curl up, squeeze hard.',
    keywords: ['spider curl'] },
  { id: 'reverse-curl', name: 'Reverse Curl', muscleGroup: 'Arms', equipment: 'Barbell', view: 'front', primary: ['forearms','biceps'],
    description: 'Overhand curl — emphasises forearms and brachioradialis.',
    instructions: '1. Pronated grip on the bar.\n2. Curl up, squeeze.\n3. Slow lower.',
    keywords: ['reverse curl'] },

  // ============ ARMS / TRICEPS ============
  { id: 'tricep-pushdown', name: 'Tricep Pushdown', muscleGroup: 'Arms', equipment: 'Cable', view: 'back', primary: ['triceps'],
    description: 'Cable isolation for the triceps.',
    instructions: '1. Grip the bar, elbows pinned.\n2. Press down to lockout.\n3. Return to ~90°.',
    keywords: ['pushdown','tricep'] },
  { id: 'rope-pushdown', name: 'Rope Pushdown', muscleGroup: 'Arms', equipment: 'Cable', view: 'back', primary: ['triceps'],
    description: 'Rope variation — flare hands at the bottom for full contraction.',
    instructions: '1. Grip the rope, elbows pinned.\n2. Press down and flare the rope.\n3. Slow return.',
    keywords: ['rope pushdown'] },
  { id: 'overhead-tricep', name: 'Overhead Tricep Extension', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'back', primary: ['triceps'],
    description: 'Stretched-position tricep work.',
    instructions: '1. Hold one dumbbell overhead with both hands.\n2. Lower behind the head.\n3. Extend back to lockout.',
    keywords: ['overhead tricep'] },
  { id: 'skullcrusher', name: 'Skullcrusher', muscleGroup: 'Arms', equipment: 'Barbell', view: 'front', primary: ['triceps'],
    description: 'Lying tricep extension with an EZ or straight bar.',
    instructions: '1. Lie on a bench, bar at arms length.\n2. Lower bar to forehead by bending elbows.\n3. Extend back up.',
    keywords: ['skullcrusher','lying tricep'] },
  { id: 'close-grip-bench', name: 'Close-Grip Bench Press', muscleGroup: 'Arms', equipment: 'Barbell', view: 'front', primary: ['triceps','chest'],
    description: 'Compound tricep builder.',
    instructions: '1. Grip shoulder-width.\n2. Tuck elbows, lower to lower chest.\n3. Press to lockout.',
    keywords: ['close grip'] },
  { id: 'diamond-pushup', name: 'Diamond Push-Up', muscleGroup: 'Arms', equipment: 'Bodyweight', view: 'front', primary: ['triceps','chest'],
    description: 'Hands close together — bodyweight tricep work.',
    instructions: '1. Form a diamond with thumbs and index fingers.\n2. Lower chest to hands.\n3. Press back up.',
    keywords: ['diamond pushup'] },
  { id: 'tricep-dip', name: 'Tricep Dip', muscleGroup: 'Arms', equipment: 'Bodyweight', view: 'front', primary: ['triceps','chest','shoulders'],
    description: 'Vertical body dip emphasising triceps.',
    instructions: '1. Stay vertical, elbows tracking back.\n2. Lower until elbows hit 90°.\n3. Press to lockout.',
    keywords: ['dip','tricep'] },
  { id: 'bench-dip', name: 'Bench Dip', muscleGroup: 'Arms', equipment: 'Bodyweight', view: 'front', primary: ['triceps'],
    description: 'Hands on a bench behind you — beginner-friendly tricep dip.',
    instructions: '1. Hands on a bench, feet on the floor.\n2. Lower hips, elbows bend back.\n3. Press up.',
    keywords: ['bench dip'] },
  { id: 'kickback', name: 'Tricep Kickback', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'back', primary: ['triceps'],
    description: 'Light isolation — strong peak contraction.',
    instructions: '1. Hinge forward, upper arm parallel to floor.\n2. Extend the forearm back.\n3. Slow return.',
    keywords: ['kickback'] },
  { id: 'jm-press', name: 'JM Press', muscleGroup: 'Arms', equipment: 'Barbell', view: 'front', primary: ['triceps'],
    description: 'Hybrid skullcrusher / close-grip press — heavy tricep mass.',
    instructions: '1. Lower the bar toward the neck with elbows tucked.\n2. Press back up.',
    keywords: ['jm press'] },

  // ============ LEGS ============
  { id: 'back-squat', name: 'Back Squat', muscleGroup: 'Legs', equipment: 'Barbell', view: 'front', primary: ['quads','glutes','abs','hamstrings'],
    description: 'The king of lower-body lifts.',
    instructions: '1. Bar on upper back.\n2. Brace, feet shoulder-width.\n3. Descend by pushing hips back and bending knees.\n4. Drive through mid-foot.',
    keywords: ['squat','back squat'] },
  { id: 'front-squat', name: 'Front Squat', muscleGroup: 'Legs', equipment: 'Barbell', view: 'front', primary: ['quads','abs','glutes'],
    description: 'Bar in front rack — heavy quad and core involvement.',
    instructions: '1. Bar in front rack, elbows high.\n2. Stay upright, descend deep.\n3. Drive up.',
    keywords: ['front squat'] },
  { id: 'goblet-squat', name: 'Goblet Squat', muscleGroup: 'Legs', equipment: 'Dumbbell', view: 'front', primary: ['quads','glutes'],
    description: 'Dumbbell or kettlebell held at chest — great for learning squat mechanics.',
    instructions: '1. Hold the weight at chest.\n2. Descend between your feet.\n3. Drive up.',
    keywords: ['goblet'] },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroup: 'Legs', equipment: 'Dumbbell', view: 'front', primary: ['quads','glutes'],
    description: 'Rear foot elevated — fantastic unilateral leg builder.',
    instructions: '1. Place rear foot on a bench.\n2. Lower front knee toward the floor.\n3. Drive through the heel.',
    keywords: ['bulgarian','split squat'] },
  { id: 'lunge', name: 'Lunge', muscleGroup: 'Legs', equipment: 'Bodyweight', view: 'front', primary: ['quads','glutes'],
    description: 'Step forward, drop the back knee, drive back to standing.',
    instructions: '1. Step forward into a long stride.\n2. Lower back knee toward the floor.\n3. Push back to standing.',
    keywords: ['lunge','forward lunge'] },
  { id: 'walking-lunge', name: 'Walking Lunge', muscleGroup: 'Legs', equipment: 'Dumbbell', view: 'front', primary: ['quads','glutes','hamstrings'],
    description: 'Continuous lunges forward — quad and glute burner.',
    instructions: '1. Step forward into a lunge.\n2. Drive up and step the other foot forward into another lunge.',
    keywords: ['walking lunge'] },
  { id: 'reverse-lunge', name: 'Reverse Lunge', muscleGroup: 'Legs', equipment: 'Dumbbell', view: 'front', primary: ['quads','glutes'],
    description: 'Step backward variation — easier on the knees than forward lunges.',
    instructions: '1. Step back into a long stride.\n2. Lower back knee.\n3. Drive front foot to stand.',
    keywords: ['reverse lunge'] },
  { id: 'leg-press', name: 'Leg Press', muscleGroup: 'Legs', equipment: 'Machine', view: 'front', primary: ['quads','glutes'],
    description: 'Plate-loaded press for the lower body — hypertrophy workhorse.',
    instructions: '1. Feet shoulder-width on the platform.\n2. Lower until knees ~90°.\n3. Drive through mid-foot.',
    keywords: ['leg press'] },
  { id: 'hack-squat', name: 'Hack Squat', muscleGroup: 'Legs', equipment: 'Machine', view: 'front', primary: ['quads','glutes'],
    description: 'Sled-based squat — strong quad emphasis.',
    instructions: '1. Shoulders under pads.\n2. Descend until thighs parallel.\n3. Drive up through the heels.',
    keywords: ['hack squat'] },
  { id: 'leg-extension', name: 'Leg Extension', muscleGroup: 'Legs', equipment: 'Machine', view: 'front', primary: ['quads'],
    description: 'Isolation for the quadriceps.',
    instructions: '1. Pad just above the ankle.\n2. Extend to lockout.\n3. Slow return.',
    keywords: ['leg extension'] },
  { id: 'leg-curl-seated', name: 'Seated Leg Curl', muscleGroup: 'Legs', equipment: 'Machine', view: 'back', primary: ['hamstrings'],
    description: 'Hamstring isolation in a seated position.',
    instructions: '1. Pad just above the heels.\n2. Curl down.\n3. Slow return.',
    keywords: ['leg curl','seated curl'] },
  { id: 'leg-curl-lying', name: 'Lying Leg Curl', muscleGroup: 'Legs', equipment: 'Machine', view: 'back', primary: ['hamstrings','glutes'],
    description: 'Prone hamstring isolation — strong stretch position.',
    instructions: '1. Lie face down, pad above the heels.\n2. Curl heels to glutes.\n3. Slow lower.',
    keywords: ['lying leg curl'] },
  { id: 'hip-thrust', name: 'Hip Thrust', muscleGroup: 'Legs', equipment: 'Barbell', view: 'back', primary: ['glutes','hamstrings'],
    description: 'The premier glute exercise.',
    instructions: '1. Upper back on a bench, bar on hips.\n2. Drive hips up to full lockout.\n3. Squeeze glutes hard.',
    keywords: ['hip thrust','glute'] },
  { id: 'glute-bridge', name: 'Glute Bridge', muscleGroup: 'Legs', equipment: 'Bodyweight', view: 'back', primary: ['glutes'],
    description: 'Floor variation of the hip thrust.',
    instructions: '1. Lie on your back, knees bent.\n2. Drive hips up.\n3. Lower under control.',
    keywords: ['glute bridge'] },
  { id: 'step-up', name: 'Step-Up', muscleGroup: 'Legs', equipment: 'Dumbbell', view: 'front', primary: ['quads','glutes'],
    description: 'Step onto a box — unilateral lower body work.',
    instructions: '1. Step onto a knee-height box.\n2. Stand up using only the lead leg.\n3. Lower with control.',
    keywords: ['step up'] },
  { id: 'calf-raise-standing', name: 'Standing Calf Raise', muscleGroup: 'Legs', equipment: 'Machine', view: 'back', primary: ['calves'],
    description: 'Standing calf raise — emphasises the gastrocnemius.',
    instructions: '1. Balls of feet on the platform.\n2. Rise as high as possible.\n3. Lower into a deep stretch.',
    keywords: ['calf raise'] },
  { id: 'calf-raise-seated', name: 'Seated Calf Raise', muscleGroup: 'Legs', equipment: 'Machine', view: 'back', primary: ['calves'],
    description: 'Bent-knee variation — emphasises the soleus.',
    instructions: '1. Pads on the lower thighs.\n2. Press up to full plantarflexion.\n3. Lower into a stretch.',
    keywords: ['seated calf'] },
  { id: 'sissy-squat', name: 'Sissy Squat', muscleGroup: 'Legs', equipment: 'Bodyweight', view: 'front', primary: ['quads'],
    description: 'Lean-back quad isolation.',
    instructions: '1. Hold support, rise on toes.\n2. Lean back, lower knees forward.\n3. Return to standing.',
    keywords: ['sissy squat'] },
  { id: 'box-squat', name: 'Box Squat', muscleGroup: 'Legs', equipment: 'Barbell', view: 'front', primary: ['glutes','quads','hamstrings'],
    description: 'Squat to a box for consistent depth and explosive drive.',
    instructions: '1. Stand in front of a box.\n2. Sit back to the box, pause.\n3. Drive up explosively.',
    keywords: ['box squat'] },
  { id: 'belt-squat', name: 'Belt Squat', muscleGroup: 'Legs', equipment: 'Machine', view: 'front', primary: ['quads','glutes'],
    description: 'Loaded at the hips — spares the spine.',
    instructions: '1. Belt around the hips.\n2. Squat to depth.\n3. Drive up.',
    keywords: ['belt squat'] },

  // ============ CORE ============
  { id: 'plank', name: 'Plank', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs','obliques','shoulders'],
    description: 'Isometric core hold.',
    instructions: '1. Forearms on the floor, elbows under shoulders.\n2. Body in a straight line.\n3. Brace and hold.',
    keywords: ['plank'] },
  { id: 'side-plank', name: 'Side Plank', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['obliques','abs'],
    description: 'Lateral plank — oblique and lateral chain work.',
    instructions: '1. On one forearm, body in a straight line.\n2. Lift hips off the floor.\n3. Hold and switch sides.',
    keywords: ['side plank'] },
  { id: 'crunch', name: 'Crunch', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs'],
    description: 'Classic short-range ab flexion.',
    instructions: '1. Lie on your back, knees bent.\n2. Curl shoulders off the floor.\n3. Slow lower.',
    keywords: ['crunch'] },
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroup: 'Core', equipment: 'Cable', view: 'front', primary: ['abs'],
    description: 'Kneeling cable crunch — load the abs heavy.',
    instructions: '1. Kneel facing the high pulley, rope behind head.\n2. Crunch torso to thighs.\n3. Slow return.',
    keywords: ['cable crunch'] },
  { id: 'russian-twist', name: 'Russian Twist', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['obliques','abs'],
    description: 'Rotational ab work.',
    instructions: '1. Sit, lean back, lift feet.\n2. Rotate side to side.\n3. Keep chest tall.',
    keywords: ['russian twist'] },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs','obliques'],
    description: 'Advanced ab move — full ROM and lat engagement.',
    instructions: '1. Hang from a bar.\n2. Raise legs to parallel or higher.\n3. Lower slowly.',
    keywords: ['hanging leg raise'] },
  { id: 'hanging-knee-raise', name: 'Hanging Knee Raise', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs'],
    description: 'Easier hanging variation.',
    instructions: '1. Hang from a bar.\n2. Raise knees to chest.\n3. Lower slowly.',
    keywords: ['hanging knee'] },
  { id: 'ab-wheel', name: 'Ab Wheel Rollout', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs','obliques','lats'],
    description: 'Brutally effective full-core movement.',
    instructions: '1. Kneel, hands on the wheel.\n2. Roll out as far as you can control.\n3. Pull back.',
    keywords: ['ab wheel','rollout'] },
  { id: 'mountain-climber', name: 'Mountain Climber', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs','shoulders','quads'],
    description: 'Dynamic plank variation — abs + conditioning.',
    instructions: '1. High plank position.\n2. Drive knees alternately to the chest.\n3. Keep hips steady.',
    keywords: ['mountain climber'] },
  { id: 'dead-bug', name: 'Dead Bug', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs'],
    description: 'Anti-extension core stability drill.',
    instructions: '1. On back, arms up, knees over hips.\n2. Lower opposite arm and leg slowly.\n3. Return and switch.',
    keywords: ['dead bug'] },
  { id: 'v-up', name: 'V-Up', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs'],
    description: 'Reach hands to feet — strong full-ab contraction.',
    instructions: '1. Lie flat, arms overhead.\n2. Simultaneously lift legs and torso to touch.\n3. Lower slowly.',
    keywords: ['v up'] },
  { id: 'bicycle-crunch', name: 'Bicycle Crunch', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs','obliques'],
    description: 'Alternating elbow-to-knee crunches.',
    instructions: '1. Lie on back, hands behind head.\n2. Bring elbow to opposite knee.\n3. Alternate sides.',
    keywords: ['bicycle crunch'] },
  { id: 'pallof-press', name: 'Pallof Press', muscleGroup: 'Core', equipment: 'Cable', view: 'front', primary: ['obliques','abs'],
    description: 'Anti-rotation core exercise.',
    instructions: '1. Stand sideways to a cable.\n2. Press the handle straight out.\n3. Resist rotation.',
    keywords: ['pallof'] },
  { id: 'l-sit', name: 'L-Sit', muscleGroup: 'Core', equipment: 'Bodyweight', view: 'front', primary: ['abs','quads','shoulders'],
    description: 'Gymnastics-style isometric ab hold.',
    instructions: '1. Hands on the floor or parallettes.\n2. Lift legs to horizontal.\n3. Hold for time.',
    keywords: ['l sit'] },

  // ============ FOREARMS ============
  { id: 'wrist-curl', name: 'Wrist Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'front', primary: ['forearms'],
    description: 'Forearm flexor isolation.',
    instructions: '1. Forearm on bench, palm up.\n2. Curl the wrist up.\n3. Slow lower.',
    keywords: ['wrist curl'] },
  { id: 'reverse-wrist-curl', name: 'Reverse Wrist Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', view: 'back', primary: ['forearms'],
    description: 'Forearm extensor isolation.',
    instructions: '1. Forearm on bench, palm down.\n2. Lift the wrist up.\n3. Slow lower.',
    keywords: ['reverse wrist'] },
  { id: 'farmers-walk', name: "Farmer's Walk", muscleGroup: 'Full Body', equipment: 'Dumbbell', view: 'front', primary: ['forearms','traps','abs','quads'],
    description: 'Loaded carry — grip, traps and full-body conditioning.',
    instructions: '1. Pick up heavy dumbbells or handles.\n2. Walk tall in a straight line.\n3. Set down with control.',
    keywords: ['farmers walk','carry'] },
  { id: 'dead-hang', name: 'Dead Hang', muscleGroup: 'Arms', equipment: 'Bodyweight', view: 'front', primary: ['forearms','lats'],
    description: 'Passive hang from a bar — grip and shoulder mobility.',
    instructions: '1. Hang from a bar with both hands.\n2. Engage shoulders slightly.\n3. Hold for time.',
    keywords: ['dead hang'] },

  // ============ CARDIO ============
  { id: 'treadmill', name: 'Treadmill', muscleGroup: 'Cardio', equipment: 'Cardio', view: 'front', primary: ['quads','calves','hamstrings'],
    description: 'Walking or running on a treadmill.',
    instructions: '1. Set incline and speed.\n2. Walk or run for the planned duration.',
    keywords: ['treadmill','run'] },
  { id: 'stationary-bike', name: 'Stationary Bike', muscleGroup: 'Cardio', equipment: 'Cardio', view: 'front', primary: ['quads','calves','glutes'],
    description: 'Low-impact cycling.',
    instructions: '1. Adjust the seat height.\n2. Pedal at the chosen intensity.',
    keywords: ['bike','cycle'] },
  { id: 'rowing-machine', name: 'Rowing Machine', muscleGroup: 'Cardio', equipment: 'Cardio', view: 'back', primary: ['back','lats','quads','glutes'],
    description: 'Full-body rowing erg.',
    instructions: '1. Drive with the legs, lean back, pull handle.\n2. Reverse: arms, lean, knees.',
    keywords: ['rowing','erg','rower'] },
  { id: 'elliptical', name: 'Elliptical', muscleGroup: 'Cardio', equipment: 'Cardio', view: 'front', primary: ['quads','glutes','calves'],
    description: 'Low-impact full-body cardio.',
    instructions: '1. Step on the pedals, hold the handles.\n2. Move smoothly for the target duration.',
    keywords: ['elliptical','cross trainer'] },
  { id: 'stair-climber', name: 'Stair Climber', muscleGroup: 'Cardio', equipment: 'Cardio', view: 'front', primary: ['quads','glutes','calves'],
    description: 'Vertical conditioning — glute and quad endurance.',
    instructions: '1. Step up steadily without leaning on the handrails.\n2. Maintain a tall posture.',
    keywords: ['stair','climber','stairmaster'] },
  { id: 'jump-rope', name: 'Jump Rope', muscleGroup: 'Cardio', equipment: 'Cardio', view: 'front', primary: ['calves','shoulders','forearms'],
    description: 'Skipping rope — calves and conditioning.',
    instructions: '1. Hold the handles, wrists rotate the rope.\n2. Small hops on the balls of the feet.',
    keywords: ['jump rope','skipping'] },

  // ============ FULL BODY / OLY ============
  { id: 'clean', name: 'Power Clean', muscleGroup: 'Full Body', equipment: 'Barbell', view: 'front', primary: ['traps','quads','glutes','back','shoulders'],
    description: 'Explosive ground-to-shoulder Olympic lift derivative.',
    instructions: '1. Set up like a deadlift.\n2. Explode, pull yourself under the bar.\n3. Catch in the front rack in a quarter squat.',
    keywords: ['clean','olympic'] },
  { id: 'snatch', name: 'Power Snatch', muscleGroup: 'Full Body', equipment: 'Barbell', view: 'front', primary: ['traps','quads','glutes','back','shoulders'],
    description: 'Explosive ground-to-overhead lift.',
    instructions: '1. Wide grip on the bar.\n2. Explode, pull under.\n3. Catch overhead in a partial squat.',
    keywords: ['snatch','olympic'] },
  { id: 'thruster', name: 'Thruster', muscleGroup: 'Full Body', equipment: 'Barbell', view: 'front', primary: ['quads','shoulders','glutes','triceps'],
    description: 'Front squat into overhead press — brutal conditioning.',
    instructions: '1. Bar in front rack.\n2. Front squat to depth.\n3. Drive up and press the bar overhead in one motion.',
    keywords: ['thruster','crossfit'] },
  { id: 'kettlebell-swing', name: 'Kettlebell Swing', muscleGroup: 'Full Body', equipment: 'Kettlebell', view: 'back', primary: ['glutes','hamstrings','back','shoulders'],
    description: 'Hip-hinge driven swing — power and conditioning.',
    instructions: '1. Hike the bell between the legs.\n2. Snap the hips, let the bell float to chest height.\n3. Let it fall back into the next rep.',
    keywords: ['kettlebell','swing','kb'] },
  { id: 'turkish-getup', name: 'Turkish Get-Up', muscleGroup: 'Full Body', equipment: 'Kettlebell', view: 'front', primary: ['shoulders','abs','obliques','glutes'],
    description: 'Floor-to-standing lift with weight overhead — full body control.',
    instructions: '1. Lie on back, press weight up.\n2. Stand up one step at a time, keeping the weight locked overhead.\n3. Reverse to lying.',
    keywords: ['turkish','get up','tgu'] },
  { id: 'burpee', name: 'Burpee', muscleGroup: 'Full Body', equipment: 'Bodyweight', view: 'front', primary: ['quads','chest','shoulders','abs'],
    description: 'Squat-thrust into a jump — full body conditioning staple.',
    instructions: '1. Squat down, kick feet back to plank.\n2. Push-up, jump feet to hands.\n3. Jump straight up.',
    keywords: ['burpee'] },
];

// ===== Sample program shipped on first load =====
const SEED_PROGRAMS = [
  {
    id: 'starter-program',
    name: 'Push Pull Legs',
    notes: 'Classic 3-day split. Repeat twice a week for higher frequency.',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    routines: [
      {
        id: 'push-day',
        name: 'Push Day',
        notes: 'Chest, shoulders, triceps',
        exercises: ['bench-press', 'ohp', 'incline-bench-press', 'lateral-raise', 'tricep-pushdown'],
      },
      {
        id: 'pull-day',
        name: 'Pull Day',
        notes: 'Back and biceps',
        exercises: ['deadlift', 'pullup', 'seated-cable-row', 'face-pull', 'bb-curl'],
      },
      {
        id: 'leg-day',
        name: 'Leg Day',
        notes: 'Quads, hamstrings, glutes',
        exercises: ['back-squat', 'rdl', 'leg-press', 'leg-curl-seated', 'calf-raise-standing'],
      },
    ],
  },
];
